DigitalClock/clock.py
Added some comments in clock.py for readability.
It's a small addition, but I'm doing it to get comfortable with Git and Open Source contribution
=> Added Comments To Clock.Py

Hex to Base64 Converter/Hex to Base64 Converter (commented).py, Hex to Base64 Converter/Hex to Base64 Converter (condensed).py, Hex to Base64 Converter/log.txt
This is a converter I had originally written for a Codewars kata. It takes as input a hexadecimal string, and provides as output the base64 conversion of the same string. There are two scripts in this; one is a more verbose script with comments explaining how the program works, and the other is condensed with shorter variable names and no excess whitespace. I also included an example log file. The hexadecimal string in the comment on line 1 of the Commented .py file is converted to the base64 string in the comment on line 2. This can be verified with the website shown in the comment on line 3.
=> Added hexadecimal to base64 converter Python script

User Hash Generator/README.md, User Hash Generator/hash.py
A hash generator to create unique hashes for each user. Random module, time and incremented integer are combined in a formule to create collusion-free short hash.
=> Adding user hash generator

Hangman/hangman.py
before editing the code, the hangman game could be played only once and then the script was done.
after the contribution the hangman game can be played until the user wishes to quit.
=> Hangman game now can be start over after one round

Get-Dir-Github-Repo/.gitignore, Get-Dir-Github-Repo/README.md, Get-Dir-Github-Repo/get.py, Get-Dir-Github-Repo/requirements.txt
Not only download them but it can filter the files by glob matching pattern to exclude or include some files.
=> Addition of script that download subdirectories from a github repository

ServerChecker/README.md, ServerChecker/serverChecker.py
=> Added Server Checker

vocabulary log helper/LogHelper.py, vocabulary log helper/LogHelperSync.py, vocabulary log helper/README.md
This pull request is for a new project, which is a vocabulary log helper. 
All other details about the project are within the README.md file
=> Plus voc log helper

BlackJackGame/BlackJackGame.py, BlackJackGame/ReadMe.md
Updating readme per conversation with @larymak.
=> Update blackjack readme

BlackJackGame/BlackJackGame.py
Blackjack function was also the win condition for getting 21. I changed the name of that function to check_Twenty_One(s) and added a check for if the number of cards == 2 to determine if the win condition should print that the player got blackjack. Otherwise, when a player receives 21, it prints "Hooray!......You made 21....etc." I did not add a condition to check that the cards are a 10 and an Ace because there is no other way to have 21 and only two cards. Thanks!
=> Update Blackjack Condition

Dictionary_Functions/README.md, Dictionary_Functions/dictionaryFunctions.py, README.md
An example of how to use dictionaries in python to call functions. This also includes an explanation of how it works.
=> Dict function

CSV_files/assets/addresses.csv, CSV_files/read_csv.py
let the function accept arguments , tuned read_using_DictReader func
=> update on CSV_files

PYTHON APPS/FinanceTracker/main.py, PYTHON APPS/FinanceTracker/settings.ui, PYTHON APPS/FinanceTracker/warning.ui
This is just an **update** of the Finance tracker. Not sure why, but some files were not uploaded in the original pull request. Here I have added the _3_ new ones to make `Finance Tracker` run.
=> Added Necessary files to run Finance Tracker

IMAGES & PHOTO SCRIPTS/Image to PDF/image2pdf.py, IMAGES & PHOTO SCRIPTS/Image to PDF/readme.md, README.md
Fixes #233 
@larymak I have added README and script files
=> Add Image to PDF

MachineLearning Projects/traffic sign recognition using CNN and Keras/Readme.md, MachineLearning Projects/traffic sign recognition using CNN and Keras/gui.py, MachineLearning Projects/traffic sign recognition using CNN and Keras/traffic_sign.py
This project is useful for identifying traffic signs with CNN and Keras.
Input: Image of the output sign: Sign classification
=> Add Trafic Sign Recognition using CNN and Keras.

MachineLearning Projects/Food-Data-Analysis/README.md, MachineLearning Projects/Food-Data-Analysis/food_menu_data.csv, MachineLearning Projects/Food-Data-Analysis/foodanalysis.ipynb
Hello, I've added this Food analysis project under the Machine learning projects folder. 
Please peruse through the project and merge the commits.
=> Added food analysis project

ART SCRIPTS/tracking live sentiment analysis to trade/Readme.md, ART SCRIPTS/tracking live sentiment analysis to trade/latest_bot.py
Fetching sentiments and prices from Reddit and Binance respectively to predict market trends
=> Automated Trading Bot for Crypto Market

PASSWORD RELATED/RandomPassword/password.py, PASSWORD RELATED/Saved Wi-FI Password/get-wifi-passwords.py
Improved overall script by adding the following:
Added error handling: The script currently only checks for a FileNotFoundError. Added more error handling to handle different types of errors that may occur.
Added a way to output the results: Currently, the script prints the results to the console. Added an option to output the results to a file.
Added support for other operating systems: The script currently only works on Windows. Added support for other operating systems like macOS and Linux.
Added the ability to delete Wi-Fi profiles: Added a function to delete Wi-Fi profiles  in case the user wants to remove saved profiles that they no longer use.
=> improved overall script added new features

MachineLearning Projects/Stock-Analysis, MachineLearning Projects/Stock-Analysis/README.md, MachineLearning Projects/Stock-Analysis/StockAnalysis.py
Added a script to compare stock price of ticker over a period and plot the finding
=> Stock analysis

SYSTEM MANAGEMENT APPS/Bookstore management/MiniProject/MiniProject/dashboard.php, SYSTEM MANAGEMENT APPS/Bookstore management/MiniProject/MiniProject/login.php, SYSTEM MANAGEMENT APPS/Bookstore management/MiniProject/MiniProject/profile.php
Deactivated ability to remove book permanently from the system
=> fixed bug and make book not permanently deleted

PYTHON APPS/GestureControlledVolume/GestureControlledVolume.ipynb, PYTHON APPS/GestureControlledVolume/README.md, PYTHON APPS/GestureControlledVolume/requirements.txt
This pull request consists the Gesture Controlled Volume project, enabling users to control their computer's audio volume using hand gestures. The project employs computer vision and hand tracking to detect hand movements and adjust the audio volume accordingly. Key highlights include:
Utilizes the MediaPipe library for real-time hand tracking.
Calculates hand gestures to control volume levels interactively.
Provides visual feedback on the video feed for a user-friendly experience.
=> Add GestureControlledVolume script

README.md
Fixing the broken Slack icon link which directs us to slack channel in [README.md](https://github.com/larymak/Python-project-Scripts/blob/main/README.md)
=> Fixing Slack Icon in Readme.Md

Cyber_security  projects/Remote Code Execution.py
Improved readability and efficiency, it makes use of Python's string manipulation capabilities for extracting the session key
=> Improved Session Key Retrieval

OTHERS/PyDiff/README.md, OTHERS/PyDiff/file1.txt, OTHERS/PyDiff/file2.txt, OTHERS/PyDiff/pydiff.py
**PyDiff** is a simple file diff utility inspired by [GNU's file diff](https://www.gnu.org/software/diffutils/).
On running, It pretty prints the diff of the given files:
=> add pydiff: A simple file diff python script

INVESTMENT_RULES/README.md, INVESTMENT_RULES/inflation_adjusted_return.py, INVESTMENT_RULES/rule_of_72.py
Created Investment_rules automation scripts.
- Added the first script that rule_of_72.py that calculate the time it takes to double your investment given the rate of fixed yearly interest rate.
=> Created Investment_rules automation scripts

gemini chatbot/chatbot.py, gemini chatbot/readme.txt, gemini chatbot/requirements.txt
🚀 Added Gemini CLI Chatbot
This PR adds a terminal-based AI chatbot built with Python and Google’s Gemini 1.5 Flash model. It enables interactive conversations directly in the command line using Google's official generativeai SDK.
✨ Features
- Streamed conversational replies from Gemini
- Python-based CLI app
- Maintains context across turns
- Easy to modify and integrate into other platforms
🛠️ Tech Stack
- Python 3.10
- Google Generative AI SDK
📦 How to Run
1. Install dependencies: `pip install -r requirements.txt`
2. Add your API key
3. Run `python chatbot.py`
Looking forward to feedback and happy to iterate on it!
=> Added Gemini Chatbot CLI version with Google Generative AI integration
