Sending-Emails/README.md
Sending-Emails/code.py
Sending-Emails/testing.txt

1. Pushed Code File
2. Added necessary Description
3. Added reference for easy to understand

Sending Email Utility Added

---

README.md

Quick access link added for shortening link utility.

Updates in Readme.md

---

YoutubeDownloader/youtube.py

Fixed the Display Window typo in the comments of the YoutubeDownloader source code for the youtube.py file

fixed spelling for Display Window comment in youtube.py code

---

InstagramBot/README.md

Fixed major typo errors in the Instagrambot Readme file and a few spelling errors

fixed Instagrambot readme typos

---

InstagramBot/README.md
PYDICTIONARY/README.md
PYDICTIONARY/pydictionary.py
README.md

Added new python dictionary Project and updated the Readme with new addition

Python dictionary

---

pyjokes/README.md

I have added the readme.md file for Pyjokes Utility

Readme.md added for Pyjokes

---

RandomPassword/password.py

Added comments ,So that beginner level python developer could understand the basic functionality of functions imported by random module.

Added comments to make it easier for beginners level Developer

---

RandomNameGen/README.md
RandomNameGen/user_generator.py

Newly getting started to open source contributions. Saw other PRs for merge to main, not sure if master is maintained separately. Please advise.

Use random instead of randint

---

Contact-management/README.md
Contact-management/contact_management.py

**Added a intermediate level python project**  
**Features available**
- CRUD operation management
- Server less database
- Contact details management

Added Intermediate Python project

---

README.md

- I have added the Image Captcha utility link to README.md.
- I have added the Python Dictionary utility link to README.md.
- Structured README.md.

Added Links to README.md and Fixed Typos

---

README.md

- I have added an Audio captcha quick link in main README.md file

Qick Link Added to README.md

---

README.md

- I have added a Quick link to the main readme.md file

"Image Grayscalling" Quick link added to main README.md

---

Weather Forcasting/README.md
Weather Forcasting/code.py

- I have added code and documentation for utility
- I have also added the README.md file to the step-by-step execution guidance
- I will update main README.md for quick link access after merging of this utility into main branch
- Please let me know if any changes to be made from my side

Weather Forcasting Utility added

---

CONTRIBUTING.md

Revise minor grammatical errors and added some engaging phrases.

Update CONTRIBUTING.md (1st paragraph only)

---

README.md
Remove Duplicate Files in Folder/entduplicate.py

Hy
I've added a project which removes duplicate files within a folder.

Added Project (Removal of Duplicate Files)

---

README.md

Added a link to the project in the readme file

added file link in readme

---

randomshuffle/random.py

Shuffling numbers

---

Age calculator/README.md
Age calculator/age.py

This is just a simple python script that perform calculation to figure out  your current age
So the math behind is  **currentTime/Year minus A birthYear**

Age-calculator

---

Rain_Alert/main.py

Rain alert

---

GAMES/Dice-Rolling-Game/Readme.md
GAMES/Dice-Rolling-Game/dice_roll_sim.py

A python script that allows multiple players to take turns rolling dice and the first player to reach 100 points wins the game.

Add Multiplayer Dice Rolling Simulator Game

---

TIME SCRIPTS/Age calculator/age.py

I have added the dyanamic year with lesser code.

dynamic year added

---

README.md

Added links to projects

---

GAMES/Snake_Game(Using Turtle)/Readme.md
GAMES/Snake_Game(Using Turtle)/snake-game.py
README.md

**What is being added**
Added Snake_Game built using turtle library of python.
-  Documentation for code.
-  Consistent coding style.
- Explanations of requirements.
-  Contains all necessary files to run code.

Added Snake_Game(Using Turtle)

---

README.md

Added Snake Game link to Readme.md

Updated Readme.md to include Snake Game

---

Data Structures and Algorithms/linked_list.py

I've added a new reverse method of the Linked List and also fixed an error in the insert method of the Linked list.

Added a new reverse method of Linked List and fixed an error in the insert method of LinkedList

---

BOTS/Chat-Bot/LICENSE
BOTS/Chat-Bot/README.md
BOTS/Chat-Bot/chatbots.py

Adding Chatbot

---

ART SCRIPTS/Images to PDF/images-to-pdf.py
AUTOMATION/Google Search Automation/google-search-automatic.py
CONVERSION SCRIPTS/CSV to JSON/csv-to-json.py
GUI/Calculator/basic-calculator-gui.py
OTHERS/URL Shortner/tiny-url-shortner.py
PASSWORD RELATED/Saved Wi-FI Password/get-wifi-passwords.py

I have added some quick python scripts that I use from time to time. I hope they are helpful and up to standard of your project.
Appreciate the compiled and organized nature of the repo! Thanks.

Included some python scripts

---

Data Structures and Algorithms/stack/README.md
Data Structures and Algorithms/stack/requirements.txt
Data Structures and Algorithms/stack/stack.py

Added a new folder stack in the data structures and algorithm folder.

Added a new folder 'stack'

---

MachineLearning Projects/Cricket Score Predictor/README.md
MachineLearning Projects/Cricket Score Predictor/app.py

I've added a cricket score predictor project under the folder "Machine learning projects", please take a gander and merge the 
the changes if everything is properly done.

added cricket score predictor project

---

Data Structures and Algorithms/bucket_sort.py

added bucket sort

---

Data Structures and Algorithms/README.md
Data Structures and Algorithms/counting_sort.py
Data Structures and Algorithms/counting_sort_2.py
Data Structures and Algorithms/radix_sort.py

Added code for the python sorting algorithms.

Added Counting Sort and Radix Sort

---

.gitmodules

Simple URL shortener app with Django

Url shortner

---

CONVERSION SCRIPTS/HTML to Excel/HTML to Excel.py
CONVERSION SCRIPTS/HTML to Excel/readme.md

added HTML to Excel conversion

added HTML to Excel conversion

---

CONVERSION SCRIPTS/HTML to Excel/HTML to Excel.py
CONVERSION SCRIPTS/HTML to Excel/readme.md
OTHERS/Star pattern/readme.md
OTHERS/Star pattern/star_pattern.py

added multiple star patters usually asked in interviews

Star pattern

---

Summarizer App/.gitignore
Summarizer App/app.py

This is a Summarizer application that summarizes ur text greater than 100 words and make it concise according to your choice. You can run my application on your device using streaml run <filename> you will have to install two libraries for that as well openai and streamlit. I couldn't deploy it because of some issues in my PC. It run's fine on local host!

New python project made by Annarhysa Albert

---

OTHERS/Secret Santa Program/README.md
OTHERS/Secret Santa Program/main.py

This is a small program used to assign people a person for Secret Santa.

Secret Santa Program

---

GUI/Password Generator/password_generator.py
GUI/Password Generator/readme.md
GUI/Password Generator/requirements.txt

This commit adds a Python script for generating strong passwords using the tkinter GUI library, as well as a readme file with usage instructions and dependencies, and a requirements file specifying the required packages and versions. The password generator script includes the ability to set the length of the password, validate user input, and copy the generated password to the clipboard.

Add password generator script

---

README.md

Updated Readme projects  with accepted pull requests

Updated Readme projects  with accepted pull requests

---

GAMES/Hangman (using classes)/README.md
GAMES/Hangman (using classes)/hangman.py

Add a hangman game created using class

Add a hangman game created using class

---

WEB SCRAPING/WebScraping-Data-Analytics/pydataanalytics.py

This project is a group work in fulfillment of our assessment in University of Lincoln

This Project is Python web scraping of  total job website with the output being sent to csv for a data analyst

---

AUDIO RELATED SCRIPTS/audiobookfinder/README.md
AUDIO RELATED SCRIPTS/audiobookfinder/audiobookfinder.py

added audiobookfinder script to audio folder

Add audiobookfinder script

---

AUTOMATION/PhotoResizing/README.md
AUTOMATION/PhotoResizing/photo_resizing.py
AUTOMATION/PhotoResizing/requirements.txt

This script automates the resizing of multiple digital images.  It resizes the original images and saves the resized images to a specified directory.
One can also archive the originals and/or delete them.
Cheers,
Jeff

New program for automatically resizing digital images.

---

Data Structures and Algorithms/README.md
Data Structures and Algorithms/radix_sort.py

Added Radix sort code in python

Added Radix sort

---

AUTOMATION/FileReplaceWithNewer/README.md
AUTOMATION/FileReplaceWithNewer/replace_with_newer.py

This program adds or copies files to a backup directory only if the source file is new or has been changed since the previous backup.

Initial commit of file copying program.

---

OTHERS/Youtube Video Downloader/README.md
OTHERS/Youtube Video Downloader/youtube-downloader.py

Youtube video downloader using python

---

FLASK PROJECTS/Instagram Scraper using Flask/.gitignore
FLASK PROJECTS/Instagram Scraper using Flask/README.md
FLASK PROJECTS/Instagram Scraper using Flask/app.py
FLASK PROJECTS/Instagram Scraper using Flask/helper.py
FLASK PROJECTS/Instagram Scraper using Flask/requirements.txt
FLASK PROJECTS/Instagram Scraper using Flask/start_server.sh

Flask website to scrape public Instagram profile with scrolling effect!

Instragram Profile Scraper using Flask

---

GUI/JSON Validator/README.md
GUI/JSON Validator/json_parser.py
GUI/JSON Validator/main.py

My first pull request. Hope I did it right! Any suggestions are welcome.

JSON Validator (GUI)

---

Cyber_security  projects/Remote Code Execution.py

Added error handling with a try-except block to manage potential exceptions and it has better readability with clear formatting and descriptive variable names

Update Remote Code Execution.py

---

FLASK PROJECTS/Excel to Firebase/main.py

improved structure and removed commented-out imports

firebase initialization

---

FLASK PROJECTS/E-commerce/app.py
FLASK PROJECTS/E-commerce/helpers.py

I am contributing an e-commerce Flask Django script. I will continuously update it and add a payment route.

Adding initial scripts for e-commerce website

---

Data Structures and Algorithms/queues.py

Added queues.py to the folder Data Structures and Algorithms which consists of code that implements queues using lists

Added queues.py with content
